config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } # для работы OmniAuth
  resources :books do
    resources :comments, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users

  root "books#index"
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  mount_uploader :avatar_title, AvatarTitleUploader

  TITLE_MAXIMUM_LENGTH = 100
  AUTHOR_MAXIMUM_LENGTH = 100
  GENRE_MAXIMUM_LENGTH = 42
  YEAR_MAXIMUM_LENGTH = 42
  DESCRIPTION_MAXIMUM_LENGTH = 580

  validates :user, presence: true
  validates :description, length: {maximum: DESCRIPTION_MAXIMUM_LENGTH}
  validates :title, presence: true, length: {maximum: TITLE_MAXIMUM_LENGTH}
  validates :author, presence: true, length: {maximum: AUTHOR_MAXIMUM_LENGTH}
  validates :avatar_title, presence: true
  validates :genre, length: {maximum: GENRE_MAXIMUM_LENGTH}
  validates :year, length: {maximum: YEAR_MAXIMUM_LENGTH}

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  BODY_MAXIMUM_LENGTH = 200

  validates :user, presence: true
  validates :book, presence: true
  validates :body, presence: true, length: {maximum: BODY_MAXIMUM_LENGTH}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable, :omniauthable


  has_many :books

  NAME_LENGTH = 30

  validates :name, presence: true, length: {maximum: NAME_LENGTH}

  # Для работы OmniAuth
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.password = Devise.friendly_token[0, 20]

      user.email = auth.info.email

      # если email не уникальный или его нету, то генерю случайный
      unless user.valid?
        count = 0
        while user.valid? == false || count != 42
          user.email = "#{rand(99999999999999)}@#{auth.provider}"
          count += 1
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :go_out

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
        :name, :email
    ])
  end

  def go_out
    if Rails.env.production?
      uri = URI(request.url)

      if uri.host == '52.38.206.116'
        uri.host = 'booksclub.tk'
        redirect_to uri.to_s
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_book, only: [:show]
  before_action :set_current_user_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all.order("created_at ASC")
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)
    @book.update_attributes(user_name: @book.user.name)

    if @book.save
      redirect_to root_path, notice: I18n.t('controllers.book.created')
    else
      render :new
    end
  end

  def show
    @new_comment = @book.comments.build(params[:comment])
  end

  def edit

  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: I18n.t('controllers.book.updated')
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy
      redirect_to root_path, notice: I18n.t('controllers.book.destroyed')
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :genre, :year, :avatar_title, :comment)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_current_user_book
    @book = current_user.books.find(params[:id])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authenticate_omniautch
  end

  def vkontakte
    authenticate_omniautch
  end

  private

  def authenticate_omniautch
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, expect: [:show, :index]
  before_action :set_book, only: [:create]
  before_action :set_comment, only: [:destroy]

  def create
      @new_comment = @book.comments.build(comment_params)
      @new_comment.user = current_user

      if @new_comment.save
        redirect_to @book, notice: 'Ваш комментарий добавлен'
      else
        render 'books/show', alert: 'Не удалось создать комментарий'
      end
  end


  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_comment
    @comment = @book.comment.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :set_current_user, only: [:edit, :update, :destroy]

  def new
    @user = current_user.build(user_params)
  end

  def show
    @user = User.find(params[:id])

    # все книги пользователя
    @books = Book.all.where(user: @user)
  end

  def edit

  end

  def update
    if @user.update(user_params)
      update_all_book_user_name_for @user # обнояю user_name книг
      redirect_to @user, notice: I18n.t('controllers.user.updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: I18n.t('controllers.user.destroyed')
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :provider, :uid)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    @user = current_user
  end

  def update_all_book_user_name_for(user)
    Book.all.where(user: user).each do |book|
      book.update_attributes(user_name: user.name)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_last_comments(condition, comments)
    if condition
      content_tag(:div, content_tag(:p, "No comment"), class: "caption")
    else
      content_tag(:div, class: "caption") { comments.collect {|item| concat(content_tag(:p, truncate(item, length: 29)))} }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  # помощь в описании
  def get_book_description(book_description)
    if !book_description.nil?
      book_description
    else
      "—"
    end
  end

  # если nil — возвращает 'Не указан'
  def get_book_params(params)
    if !params.nil?
      params
    else
      "Не указан"
    end
  end
end

# склонятор автор, авторы
def sklonyator(author)
  if author.include?(" и ") || author.include?(" and ")
    "Авторы"
  else
    "Автор"
  end
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<!-- Паршиал отображения инфы об отдельной книге -->

<div class="col-sm-4 col-md-2">
  <div class="thumbnail">
    <%= render_last_comments(book.comments.empty?, book.comments.last(3).map(&:body)) %>
  </div>
</div>

<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <div class="caption">
      <h3><%= link_to book.title, book_path(book) %></h3>
      <p> <%= image_tag book.avatar_title.thumb %> </p>
      <p class="buffer-top"><em><%= sklonyator(book.author) %>: <%= book.author %></em></p>

    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

    <%= render partial: 'partials/form_errors', locals: {model: @book} %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', maxlength: Book::TITLE_MAXIMUM_LENGTH %>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control', maxlength: Book::AUTHOR_MAXIMUM_LENGTH %>
    </div>

    <div class="form-group">
      <%= f.label :genre %>
      <%= f.text_field :genre, class: 'form-control', maxlength: Book::GENRE_MAXIMUM_LENGTH %>
    </div>

    <div class="form-group">
      <%= f.label :year %>
      <%= f.text_field :year, class: 'form-control', maxlength: Book::YEAR_MAXIMUM_LENGTH %>
    </div>

    <div class="form-group">
      <%= f.label :avatar_title %>
      <p><%= image_tag(@book.avatar_title.thumb.url) if @book.avatar_title? %></p>
      <%= f.file_field :avatar_title %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <span style="float: right;">
        Осталось <span id="count1"><%= Book::DESCRIPTION_MAXIMUM_LENGTH %> </span> символов
      </span>
      <%= f.text_area :description, class: 'form-control', id: 'contentbox1', maxlength: Book::DESCRIPTION_MAXIMUM_LENGTH %>
    </div>

    <div class="action buffer-bottom">
      <%= f.submit 'Сохранить', class: 'btn btn-success' %>
      <% if @book.persisted? %>
        <%= link_to 'Удалить', @book, method: :delete, data: {confirm: 'Действительно удалить книгу?'}, class: 'btn btn-danger' %>
          или <%= link_to 'вернуться', :back %>
      <% end %>
    </div>

<% end %>

app/views/books/edit.html.erb
<h1>Редактирование книги</h1>

<div class="row">
  <div class="col-sm-4 col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/books/index.html.erb
<h1>Книги</h1>

<div class="buffer-bottom">
  <%= link_to 'Выложить книгу', new_book_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <!-- Рендерю массив всех книг из паршела books/book -->
  <div class="flex-container">

  <%= render partial: 'books/book', collection: @books %>

  </div>
</div>

app/views/books/new.html.erb
<h1>Новая книга</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @book.title %></h1>
    <% if @book.user.present? %>
        <p>Выложил: <strong><%= link_to @book.user.name, user_path(@book.user) %></strong></p>
    <% else %>
        <% if @book.user_name.present? %>
            <p>Выложил: <strong><%= @book.user_name %></strong></p>
        <% end %>
    <% end %>
  </div>
</div>

<% if current_user == @book.user && @book.user.present? %>
    <div class="buffer-bottom">
      <%= link_to 'Редактировать', edit_book_path, class: 'btn btn-primary' %>
    </div>
<% end %>

<div class="row thumbnail">
  <div class="col-sm-6">
    <div class="caption">
      <p> <%= image_tag @book.avatar_title if @book.avatar_title? %> </p>
    </div>
  </div>

  <div class="col-sm-6">
    <h4>Описание</h4>
    <p><%= get_book_description(@book.description) %></p><br>
    <p><em><%= sklonyator(@book.author) %>: <%= get_book_params(@book.author) %></em></p>
    <p><em>Жанр: <%= get_book_params(@book.genre) %></em></p>
    <p><em>Год выпуска: <%= get_book_params(@book.year) %></em></p>
  </div>
</div>

<% if user_signed_in? %>
    <div class="buffer-top">
      <%= render partial: 'comments/form', locals: {comment: @new_comment || @book.comments.build} %>
    </div>
<% end %>


<div class="buffer-bottom buffer-top">
  <%= render partial: 'comments/comment', collection: @book.comments.except(@new_comment) %>
</div>

app/views/comments/_comment.html.erb
<div class="buffer-bottom">
  <p class="norm-width"><%= comment.body %></p>
  <p>
    <span>
      <em><strong><%= comment.user.name %></strong></em>
    </span>
    <em><%= l comment.created_at, format: :short %></em>

  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@book, comment] do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: comment} %>

    <div class="form-group">
      <%= f.label :body %>
      <span style="float: right;">
        Осталось <span id="count2"><%= Comment::BODY_MAXIMUM_LENGTH %> </span> символов
      </span>
      <%= f.text_area :body, class: 'form-control', maxlength: Comment::BODY_MAXIMUM_LENGTH, id: 'contentbox2' %>
    </div>

    <div class="actions">
      <%= f.submit 'Отправить', class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "BooksClub" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="mailru-domain" content="77X7VyHdlGy3Nk9o" />
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href=<%= root_path %>>BooksClub</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if current_user.present? %>
            <li><%= link_to 'Профиль', user_path(current_user) %></li>
            <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to 'Войти', new_user_session_path %></li>
            <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  </div><!--/row-->

</div> <!-- /container -->

<footer class="footer">
  <div class="container">
    <p>&copy; <%= I18n.t('app.company') %></p>
  </div>
</footer>



</body>
</html>

app/views/partials/_form_errors.html.erb
<!-- Универсальный паршиал отображения ошибок валидации любой модели -->

<% errors = model.errors %>

<% if errors.any? %>
    <div class="alert alert-danger">
      <div class="lead buffer-bottom">
        В вашей форме <%= errors.count %>
        <%= Russian.p(errors.count, "ошибка", "ошибки", "ошибок") %>
      </div>

      <ul>
        <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <%= render partial: 'partials/form_errors', locals: {model: @user} %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="action buffer-bottom">
      <%= f.submit 'Сохранить', class: 'btn btn-success' %>
      <%= link_to 'Удалить', @user, class: 'btn btn-danger', method: :delete,
                  data: {confirm: 'Вы действительно хотите удалить аккаунт?'} %>
      или <%= link_to 'вернуться', :back %>
    </div>

<% end %>

app/views/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<div class="row">
  <div class="col-sm-4 col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<p>Пользователь: <strong><%= @user.name %></strong></p>

<% if current_user == @user %>
    <%= link_to 'Редактировать', edit_user_path(@user), class: 'btn btn-primary' %>
<% end %>

<% if @user.books.size > 0 %>
    <h3>Выложенные книги</h3>

    <div class="row buffer-bottom">
      <div class="flex-container">

        <%= render partial: 'books/book', collection: @books %>

      </div>
    </div>
<% else %>
    <h3>Пользователь не выложил ни одной книги</h3>
<% end %>